management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,prometheus'     #'health,metrics'
  endpoint:
    health:
      enabled: true
      show-details: always
#    metrics:
#      enabled: true
    prometheus:
      enabled: true